# Generated by Django 4.2.16 on 2024-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0004_textlinevideoclip_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='lead-maker/text_file'),
        ),
    ]
