# Generated by Django 4.2.16 on 2025-01-10 07:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0005_textfile_text_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textfile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='timestamp_end',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='timestamp_start',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='trimmed_video',
        ),
        migrations.RemoveField(
            model_name='textfile',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='text',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='timestamp_end',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='timestamp_start',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='video_file_path',
        ),
        migrations.AddField(
            model_name='textfile',
            name='bg_level',
            field=models.DecimalField(blank=True, decimal_places=9, default=0.1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='textfile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='textfile',
            name='generated_subclips_srt',
            field=models.FileField(blank=True, null=True, upload_to='generated_subclips_srt/'),
        ),
        migrations.AddField(
            model_name='textfile',
            name='subclips_text_file',
            field=models.FileField(blank=True, null=True, upload_to='subclips_text_files/'),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='remaining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='slide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lead_maker/text_clip_upload_videos/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_files'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='bg_music_text',
            field=models.FileField(blank=True, null=True, upload_to='background_txt/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='blank_video',
            field=models.FileField(blank=True, null=True, upload_to='blank_video/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='font',
            field=models.CharField(default='Arial', max_length=50),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_audio',
            field=models.FileField(blank=True, null=True, upload_to='generated_audio/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_blank_video',
            field=models.FileField(blank=True, null=True, upload_to='generated_blank_video/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_final_bgm_video',
            field=models.FileField(blank=True, null=True, upload_to='generated_bgm_video/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_final_bgmw_video',
            field=models.FileField(blank=True, null=True, upload_to='generated_bgmw_video/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_final_video',
            field=models.FileField(blank=True, null=True, upload_to='generated_final_video/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_srt',
            field=models.FileField(blank=True, null=True, upload_to='generated_srt/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='generated_watermarked_video',
            field=models.FileField(blank=True, null=True, upload_to='generated_watermarked_video/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='srt_file',
            field=models.FileField(blank=True, null=True, upload_to='srt_files/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='textfile',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.text_file_upload_path),
        ),
        migrations.CreateModel(
            name='SubClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtittle', models.CharField(max_length=100)),
                ('start', models.DecimalField(blank=True, decimal_places=6, default=0.1, max_digits=12, null=True)),
                ('end', models.DecimalField(blank=True, decimal_places=6, default=0.1, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position_in_slide', models.IntegerField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to=mainapps.vidoe_text.models.text_clip_upload_path)),
                ('main_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclips', to='vidoe_text.textlinevideoclip')),
            ],
            options={
                'ordering': ['main_line__slide', 'position_in_slide'],
            },
        ),
    ]
