# Generated by Django 4.2.16 on 2025-01-10 08:07

from django.db import migrations, models
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0006_alter_textfile_options_remove_textfile_timestamp_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='trimmed_video',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.video_file_upload_path),
        ),
        migrations.AddField(
            model_name='textfile',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.video_file_upload_path),
        ),
    ]
