# Generated by Django 4.2.16 on 2025-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0008_textfile_timestamp_end_textfile_timestamp_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textlinevideoclip',
            options={'ordering': ['position', 'line_number', 'text_file']},
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
