# Generated by Django 4.2.16 on 2025-02-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0009_alter_textlinevideoclip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='is_tiktok',
            field=models.BooleanField(default=False),
        ),
    ]
